i18n for LeanCloud specific features
leancloud/ticket pull request #135
Opened 2020-12-27 10:31 UTC by weakish

2021-01-05 13:36 UTC, weakish commented
部署到了工单的预备环境，可以在线测试。

2021-01-06 03:06 UTC, shifuchen98 requested changes

2021-01-06 03:06 UTC, shifuchen98 commented on modules/i18n/locales.js
> +    'To display applications in other regions, please link them first at Settings > Linked accounts',
```suggestion
    'To display applications in other regions, please first link them at Settings > Linked accounts',
```

2021-01-06 03:06 UTC, shifuchen98 commented on modules/i18n/locales.js
> +    'mobile',
```suggestion
    'Mobile',
```

2021-01-06 03:06 UTC, shifuchen98 commented on modules/i18n/locales.js
> +    'region',
```suggestion
    'Region',
```

2021-01-06 05:07 UTC, shifuchen98 approved these changes

2021-01-06 05:07 UTC, merged